package mysource.system.entity;

import java.io.Serializable;
import java.util.Date;

public class ManAuthentication implements Serializable {
    private Long iid;

    /** 登录目标 */
    private String slogintarget;

    /** 身份标识，多合一验证时，以/分割 */
    private String sprincipal;

    /** 验证凭证 */
    private String scredential;

    /** web访问地址 */
    private String sweburi;

    /** 凭证更新时间 */
    private Date scredtime;

    /** 描述信息 */
    private String sdesccription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_authentication
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_authentication.IID
     *
     * @return the value of man_authentication.IID
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public Long getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_authentication.IID
     *
     * @param iid the value for man_authentication.IID
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public void setIid(Long iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_authentication.SLOGINTARGET
     *
     * @return the value of man_authentication.SLOGINTARGET
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public String getSlogintarget() {
        return slogintarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_authentication.SLOGINTARGET
     *
     * @param slogintarget the value for man_authentication.SLOGINTARGET
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public void setSlogintarget(String slogintarget) {
        this.slogintarget = slogintarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_authentication.SPRINCIPAL
     *
     * @return the value of man_authentication.SPRINCIPAL
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public String getSprincipal() {
        return sprincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_authentication.SPRINCIPAL
     *
     * @param sprincipal the value for man_authentication.SPRINCIPAL
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public void setSprincipal(String sprincipal) {
        this.sprincipal = sprincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_authentication.SCREDENTIAL
     *
     * @return the value of man_authentication.SCREDENTIAL
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public String getScredential() {
        return scredential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_authentication.SCREDENTIAL
     *
     * @param scredential the value for man_authentication.SCREDENTIAL
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public void setScredential(String scredential) {
        this.scredential = scredential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_authentication.SWEBURI
     *
     * @return the value of man_authentication.SWEBURI
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public String getSweburi() {
        return sweburi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_authentication.SWEBURI
     *
     * @param sweburi the value for man_authentication.SWEBURI
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public void setSweburi(String sweburi) {
        this.sweburi = sweburi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_authentication.SCREDTIME
     *
     * @return the value of man_authentication.SCREDTIME
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public Date getScredtime() {
        return scredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_authentication.SCREDTIME
     *
     * @param scredtime the value for man_authentication.SCREDTIME
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public void setScredtime(Date scredtime) {
        this.scredtime = scredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_authentication.SDESCCRIPTION
     *
     * @return the value of man_authentication.SDESCCRIPTION
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public String getSdesccription() {
        return sdesccription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_authentication.SDESCCRIPTION
     *
     * @param sdesccription the value for man_authentication.SDESCCRIPTION
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    public void setSdesccription(String sdesccription) {
        this.sdesccription = sdesccription;
    }
}