package mysource.system.dao;

import mysource.system.entity.ManAuthentication;

public interface ManAuthenticationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_authentication
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    int deleteByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_authentication
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    int insert(ManAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_authentication
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    int insertSelective(ManAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_authentication
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    ManAuthentication selectByPrimaryKey(Long iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_authentication
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    int updateByPrimaryKeySelective(ManAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_authentication
     *
     * @mbggenerated Mon Oct 24 14:50:15 CST 2016
     */
    int updateByPrimaryKey(ManAuthentication record);
}